Run node -e "
/home/runner/work/_temp/d2a2335f-996d-4115-9a65-76dca139f5b3.sh: line 1: ./songs/${normalize(artist)}-${normalize(title)}.txt: bad substitution
/home/runner/work/_temp/d2a2335f-996d-4115-9a65-76dca139f5b3.sh: line 1: ${songs.length}: bad substitution
[eval]:109
      };
      ^

SyntaxError: Unexpected token '}'
    at makeContextifyScript (node:internal/vm:185:14)
    at node:internal/process/execution:107:22
    at [eval]-wrapper:6:24
    at runScript (node:internal/process/execution:101:62)
    at evalScript (node:internal/process/execution:133:3)
    at node:internal/main/eval_string:51:3

Node.js v20.20.2
Error: Process completed with exit code 1.
